version:  "3.4"

services: 
  swiftmeal:
    image: swiftmeal
    build: .
    environment:  
      NODE_ENV: production
    ports: 
      - 3000:3000
    volumes: 
      - .:/usr/src/swiftmeal
    links: 
      - mongodb
  mongodb:
    image: mongo:latest
    ports: 
      - 27017:27017
    volumes: 
      - data:/data/db

volumes: 
  data: